# Generated by Django 2.2.12 on 2021-12-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
