# Generated by Django 2.2.12 on 2021-12-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_on',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
