# Generated by Django 2.2.12 on 2021-11-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='title',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='users',
        ),
        migrations.RemoveField(
            model_name='events',
            name='category',
        ),
        migrations.RemoveField(
            model_name='like',
            name='title',
        ),
        migrations.RemoveField(
            model_name='like',
            name='users',
        ),
        migrations.DeleteModel(
            name='Booked',
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
