# Generated by Django 2.2.12 on 2021-12-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liketest',
            name='liked',
        ),
    ]
