# Generated by Django 2.2.12 on 2021-12-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_booked_dislike_events_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='title',
            new_name='name',
        ),
    ]
