# Generated by Django 2.2.12 on 2021-12-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_liketest_liked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='liketest',
            unique_together=set(),
        ),
    ]
