# Generated by Django 2.2.12 on 2021-12-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20211201_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='dislike',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='name',
            new_name='title',
        ),
    ]
